spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/medvault
    username: medvault_user
    password: medvault_password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/medvault
    user: medvault_user
    password: medvault_password

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:1800000} # 30 minutes in ms

logging:
  level:
    com.medvault: DEBUG
